### ISSUE TITLE
Nicer shell variables

### ISSUE THREAD

**Issue by BrandonIngalls** [siadat/gosetup#1]
The current way gosetup deals with bash / zsh variables is not very clean.  It could be modified to the following.

``` go
s := fmt.Sprintf("export GOPATH='%s'\nexport PATH=\"${PATH}${PATH:+:}${GOPATH}/bin\"", gopath)
```

Would result in 

> export GOPATH='/home/brandoni/Go'
> export PATH="${PATH}${PATH:+:}${GOPATH}/bin"

**Comment by siadat** [comment]
Thanks for your suggestions!

Could you explain in what conditions `${PATH:+:}` is not the same as `:`?

**Comment by BrandonIngalls** [comment]
When the PATH has not already been evaluated, which I have seen some crazy things being done in a `.bashrc` or `.zshrc` file where that could be true.

``` bash
[~]$ echo "${PATH}"

[~]$ export PATH="${PATH}${PATH:+:}${HOME}/bin"

[~]$ echo "${PATH}"                            
/home/brandoni/bin
```

It is not a big deal, but it can lead to a cleaner PATH.

``` bash
[~]$ echo "${PATH}"

[~]$ export PATH="${PATH}:${HOME}/bin"

[~]$ echo "${PATH}"                   
:/home/brandoni/bin
```

**Comment by siadat** [comment]
@BrandonIngalls Thank you!
